<?xml version="1.0" encoding="EUC-KR"?>
<!DOCTYPE BookCatalog [
	<!ELEMENT BookCatalog (Book*)>  <!-- BookCatalog의 하위요소 Book 여러개 -->
	<!ELEMENT Book (Title, Author, Year)>
	<!ELEMENT Title (#PCDATA)>
	<!ELEMENT Author (#PCDATA)>
	<!ELEMENT Year (#PCDATA)>
]>
<BookCatalog>
	<Book>
		<Title>Harry Potter 1</Title>
		<Author>J. K. Rowling</Author>
		<Year>2001</Year>
	</Book>
	<Book>
		<Title>Charlie and the Chocolate Factory</Title>
		<Author>Roald Dahl</Author>
		<Year>2012</Year>
	</Book>
	<Book>
		<Title>The Giver</Title>
		<Author>Lois Lowry</Author>
		<Year>1993</Year>
	</Book>
</BookCatalog>
