<!-- -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BookCatalog [
	<!ELEMENT BookCatalog (Book*)>
	<!ELEMENT Book ( (Title | BookCode), CoAuthor, Year, Summary)>
	<!ELEMENT Title (#PCDATA)>
	<!ELEMENT BookCode (#PCDATA)>
	<!ELEMENT Author (#PCDATA)>
	<!ELEMENT CoAuthor (#PCDATA | Author)*>
	<!ELEMENT Year (#PCDATA)>
	<!ELEMENT Summary ANY>
	<!ATTLIST Book code ID #IMPLIED>
]>
<BookCatalog>
	<Book code = "내책1">
		<Title>Harry Potter</Title>
		<CoAuthor>
			주저자: <Author> J. K. Rowling </Author>
			공저자: <Author> 구예지 </Author>
		</CoAuthor>
		<Year>2001</Year>
		<Summary><![CDATA[해리포터 & 론 & 헤르미온느]]></Summary>
	</Book>
	<Book code = "내책1">
		<Title>Harry Potter</Title>
		<CoAuthor>
			주저자: <Author> J. K. Rowling </Author>
			공저자: <Author> 구예지 </Author>
		</CoAuthor>
		<Year>2001</Year>
		<Summary><![CDATA[해리포터 & 론 & 헤르미온느]]></Summary>
	</Book>
</BookCatalog>
