=== xlzbthxyjkoo/XML-practice/1010/ex4-7.xsd
<?xml version="1.0" encoding="UTF-8">
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://cs.skuniv.ac.kr/xml/yjkoo"
    xmlns:target="http://cs.skuniv.ac.kr/xml/yjkoo"
    elementFormatDefault="qualified">

    <simpleType name = "HourScope">
	<restriction base = "int">
	    <minInclusive value="0" />
	    <maxExclusive value="10" />
	</restriction>
    </simpleType>
    <simpleType name = "MinuteScope">
	<restriction base="int">	
	    <minInclusive value="0" />
	    <maxExclusive value="60" />
	</restriction>
    </simpleType>
    <simpleType name="SecondScope">
	<restriction base="int">
	    <minInclusive value="0" />
	    <maxExclusive value="60" />
	</restriction>
    </simpleType>
 
    <group name="Album">
	<sequence>
	    <element name="Title" type="string"/>
	    <element name="Artist" type="string"/>
	    <element name="Genre" type="string"/>
	    <element name="Released-date" type="string"/>
	    <element name="Song" maxOccurs="unbounded">
		<complexType>
		    <sequence>
			<element name="hours" type="target:HourScope" />
			<element name="minutes" type="target:MinuteScope"/>
			<element name="seconds" type="target:SecondScope"/>
		    </sequence>
		</complexType>
	    </element>
	</sequence>
    </group>

    <element name="AudioCatalog">
	<complexType>
	    <choice maxOccurs="unbounded">
		<element name="Cd">
		    <complexType>
			<group ref="target:Album"/>
		    </complexType>
		</element>
		<element name="Record">
		    <complexType>
			<group ref="target:Album"/>
		    </complexType>
		</element>
		<element name="Mp3">
		    <complexType>
			<group ref="target/Album"/>
		    </complexType>
		</element>
	    </choice>
	</complexType>
    </element>
</schema>

=== xlzbthxyjkoo/XML-practice/1010/ex4-7.xml
<?xml version="1.0" encoding="UTF-8"?>
<AudioCatalog xmlns="http://cs.skuniv.ac.kr/xml/yjkoo"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://cs.skuniv.ac.kt/xml/yjkoo ex4-7.xsd">

    <Cd>
	<Title> 뉴진스 1집 </Title>
	<Artist> New Jeans </Artist>
	<Genre> kpop </Genre>
	<Released-date> 2022 </Released-date>
	<Song> Hype Boy
	    <PlayTime>
		<hours> 1 </hours>
		<minutes> 2 </minutes>
		<seconds> 30 </seconds>
	    </PlayTime>
	</Song>
	<Song> Attention 
	    <PlayTime>
		<hours> 4 </hours>
		<minutes> 34 </minutes>
		<seconds> 44 </seconds>
	    </PlayTime>
	</Song>
	<Song> Cookie
	    <PlayTime>
		<hours> 1 </hours>
		<minutes> 22 </minutes>
		<seconds> 33 </seconds>
	    </PlayTime>
	</Song>
    </Cd>

    <Record>
	<Title> 뉴진스 2집 </Title>
	<Artist> New Jeans </Artist>
	<Genre> kpop </Genre>
	<Released-date> 2022 </Released-date>
	<Song> Hype Boy
	    <PlayTime>
		<hours>0</hours>
		<minutes>3</minutes>
		<seconds>33</seconds>
	    </PlayTime>
	</Song>
	<Song> Attention
	    <PlayTime>
		<hours>0</hours>
		<minutes>4</minutes>
		<seconds>32</seconds>
	    </PlayTime>
	</Song>

	<Song> Cookie
	    <PlayTime>
		<hours>0</hours>
		<minutes>1</minutes>
		<seconds>23</seconds>
	    </PlayTime>
	</Song>
    </Record>
    <Mp3>
	<Title> 뉴진스 3집 </Title>
	<Artist> New Jeans </Artist>
	<Genre> kpop </Genre>
	<Released-date> 2022 </Released-date>
	<Song> Hype Boy
	    <PlayTime>
		<hours>3</hours>
		<minutes>3</minutes>
		<seconds>2</seconds>
	    </PlayTime>
	</Song>

	<Song> Attention 
	    <PlayTime>
		<hours>3</hours>
		<minutes>2</minutes>
		<seconds>1</seconds>
	    </PlayTime>
	</Song>
	<Song> Cookie 
	    <PlayTime>
		<hours>1</hours>
		<minutes>1</minutes>
		<seconds>1</seconds>
	    </PlayTime>
	</Song>
    </Mp3>
</AudioCatalog>
